### PR TITLE
Fix the updated JRPG demo for Godot 4.0

### PR DESCRIPTION
**Pull request by Nonparoxysmic**
This fixes the fatal issues in the JRPG demo with updated art assets for Godot 4.

- Bugs were fixed in GDScript files and in the scene trees.
- Small improvements were made to some UI elements.
- Scene files that were edited were automatically converted to Format 3 by the engine.

This work was performed and tested in Godot 4.0.4.

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for carrying out this work! It's highly appreciated :slightly_smiling_face: 

I've tested this branch on Godot 4.1.1 and can notice an issue with character movement. It gets softlocked if you press a movement key twice or hold it down long enough (possibly due to key echo events). The square permanently appears outside the character in this case.

https://github.com/Calinou/godot-demo-projects/assets/180032/83abed04-31ac-48b3-b7a4-b7c53919985d

The NPC still animates after this softlock, but not the player sprite.

The rest (combat, finding the key) seems to work fine, although ProgressBar theming in the UI (used for health bars during combat) was lost during the transition.

**Comment by Nonparoxysmic** [comment]
Thank you! This is my bad for not testing in 4.1 as well.

I think the issue is where I have the player character's movement script awaiting signals from the AnimationTree. Something appears to be different in 4.1 that is causing those signals to work in a way I didn't expect. I'll do more research and see if I can find a good solution.

I believe I can restore some theming to the health bars so I will do that also.

**Comment by Nonparoxysmic** [comment]
I think I have fixed those issues now. Tested in 4.0.4 and 4.1.2.

**Review by Calinou — APPROVED** [review]
Tested on 4.1.1, works great! Thanks a lot :slightly_smiling_face:

**Pull request merged**
