### PR TITLE
Add a new "Gradients" scene to Color Correction and Tone Mapping

### PR DESCRIPTION
**Pull request by allenwp**
This PR adds a new "Gradients" scene to the color correction and tone mapping domo. This scene allows the user to see how different tone mappers behave over a range of values, which helps identify issues with hue shift, etc.

image
image
image
image

### CODE REVIEW

**Comment by allenwp** [comment]
I've updated the PR to add an exponential scale option. This makes it easier to view the darker values:
image

**Comment by allenwp** [comment]
And I've added one more scene that shows a saturated RGB hue gradient:
image

I will be honest, there are probably improvements that should be made regarding scene structure if this was to be merged as an official Godot demo project. For example, my controls could send signals instead of being hard-linked to various nodes.

I wanted to submit this PR to you as-is before spending a lot of time cleaning it up because I'm not sure if you want these sort of changes in your project in the first place.

**Comment by Calinou** [comment]
This looks great 🙂 

Could you look into rebasing this to resolve merge conflicts so I can merge this?

**Comment by allenwp** [comment]
Rebased, no conflicts!

**Comment by allenwp** [comment]
I figure you will squash my commits into yours, but let me know if you’d prefer me to squash mine separate from yours.

**Comment by Calinou** [comment]
> I figure you will squash my commits into yours, but let me know if you’d prefer me to squash mine separate from yours.

It's fine, I use *Squash and merge* here and the final PR will be squashed into a single commit anyway.

**Comment by allenwp** [comment]
I see formatting checks are failing. I can reformat this at some point if you’d like.

**Pull request merged**
